In [57]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [58]:
tokenizer = Tokenizer()

In [59]:
data = "# Example Python code snippets # 1. Basic arithmetic operations x = 5 y = 3 sum = x + y  # Addition difference = x - y  # Subtraction product = x * y  # Multiplication quotient = x / y  # Division remainder = x % y  # Modulus (remainder after division) print(\"Sum:\", sum) print(\"Difference:\", difference) print(\"Product:\", product) print(\"Quotient:\", quotient) print(\"Remainder:\", remainder) # 2. Conditional statements (if-else) age = 25 if age >= 18: print(\"You are an adult.\") else: print(\"You are a minor.\") # 3. Loops (for loop) for i in range(5): print(i)  # Prints numbers from 0 to 4 # 4. Functions def greet(name): print(\"Hello,\", name + \"!\") greet(\"Alice\")  # Output: Hello, Alice! # 5. Lists fruits = [\"apple\", \"banana\", \"orange\"] print(fruits[0])  # Accessing the first element (apple) fruits.append(\"grape\")  # Adding an element to the list print(fruits) # 6. Dictionaries student = {\"name\": \"John\", \"age\": 20, \"major\": \"Computer Science\"} print(student[\"name\"])  # Accessing the value associated with the key \"name\" # 7. Working with files try: with open(\"my_file.txt\", \"r\") as file: content = file.read() print(content) except FileNotFoundError: print(\"File not found.\") # 8. Classes and objects (basic example) class Dog: def __init__(self, name): self.name = name def bark(self): print(\"Woof!\") my_dog = Dog(\"Buddy\") print(my_dog.name) my_dog.bark()  # Output: Woof! # 9. Using external libraries import math result = math.sqrt(25)  # Calculate the square root of 25 print(result)"


In [60]:
tokenizer.fit_on_texts([data])

In [61]:
input_sequences = []

In [62]:
for line in data.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range (1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [63]:
input_sequences

[[21, 48],
 [21, 48, 49],
 [21, 48, 49, 50],
 [21, 48, 49, 50, 51],
 [21, 48, 49, 50, 51, 22],
 [21, 48, 49, 50, 51, 22, 52],
 [21, 48, 49, 50, 51, 22, 52, 53],
 [21, 48, 49, 50, 51, 22, 52, 53, 3],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23, 12],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23, 12, 3],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23, 12, 3, 4],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23, 12, 3, 4, 54],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23, 12, 3, 4, 54, 13],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23, 12, 3, 4, 54, 13, 3],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23, 12, 3, 4, 54, 13, 3, 4],
 [21, 48, 49, 50, 51, 22, 52, 53, 3, 11, 4, 23, 12, 3, 4, 54, 13, 3, 4, 55],
 [21,
  48,
  49,
  50,
  51,
  22,
  52,
  53,
  3,
  11,
  4,
  23,
  12,
  3,
  4,
  54,
  13,
  3,
  4,
  55,
  14],
 [21,
  48,
  49,
  50,
  

In [64]:
max_lenghth = 0
for i in range(len(input_sequences)):
    if len(input_sequences[i]) > max_lenghth:
        max_lenghth = len(input_sequences[i])
print(max_lenghth)

222


In [65]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
input_sequences = pad_sequences(input_sequences, maxlen=max_lenghth, padding='pre')
print(input_sequences)

[[  0   0   0 ...   0  21  48]
 [  0   0   0 ...  21  48  49]
 [  0   0   0 ...  48  49  50]
 ...
 [  0   0  21 ... 120 121  17]
 [  0  21  48 ... 121  17   1]
 [ 21  48  49 ...  17   1  47]]


In [66]:
x = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [67]:
x

y

array([ 48,  49,  50,  51,  22,  52,  53,   3,  11,   4,  23,  12,   3,
         4,  54,  13,   3,   4,  55,  14,   3,   4,  56,  15,   3,   4,
        24,   7,   3,   4,  57,   7,  58,  24,   1,  12,  12,   1,  13,
        13,   1,  14,  14,   1,  15,  15,   1,   7,   7,  59,  60,  61,
        25,  26,  16,  17,  25,  16,  62,   1,  27,  28,  29,  63,  26,
         1,  27,  28,  64,  65,  23,  66,  30,  67,  30,  31,  68,  69,
        11,   1,  31,  70,  71,  72,  32,  33,  34,  34,  73,  18,  35,
         2,   1,  36,   2,  35,  37,  38,  36,  37,  11,  74,   8,  39,
        75,  76,   1,   8,  32,  40,   5,  77,  41,  39,   8,  78,  79,
        80,  29,  41,  33,   5,  81,   1,   8,  82,  83,  42,   2,  84,
        16,  85,  86,  87,  88,   1,  42,   2,  40,   5,  89,  90,  19,
         5,  91,   2,  92,  93,  19,  94,  95,  19,  96,   9,  10,  97,
        98,  99,  10,  43,  10, 100,   1,  43, 101, 102,   1,  10, 103,
       104, 105, 106, 107, 108,  22,  21, 109,   6,  18, 110,  2

In [68]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [69]:
from ast import mod
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=10))
model.add(LSTM(100))
model.add(Dense(len(tokenizer.word_index)+1, activation='softmax'))

In [70]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [71]:
model.fit(x,y, epochs = 100)

Epoch 1/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.0264 - loss: 4.8036
Epoch 2/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0830 - loss: 4.7952
Epoch 3/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0795 - loss: 4.7691
Epoch 4/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0653 - loss: 4.6448
Epoch 5/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0671 - loss: 4.6166
Epoch 6/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0648 - loss: 4.5673
Epoch 7/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0665 - loss: 4.5552
Epoch 8/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0709 - loss: 4.4938
Epoch 9/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0689 - loss: 4.5273
Epoch 10/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0712 - loss: 4.5595
Epoch 11/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0597 - loss: 4.4782
Epoch 12/100
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.1004 - lo

In [72]:
import numpy as np
text = "while"


In [74]:
for i in range(5):
  token_text = tokenizer.texts_to_sequences([text])[0]
  token_text = pad_sequences([token_text], maxlen = max_lenghth, padding = 'pre')
  prob = model.predict(token_text)
  pos = np.argmax(prob)
  for word, index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
while python python python python code 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
while python python python python code 1 arithmetic
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
while python python python python code 1 arithmetic arithmetic
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
while python python python python code 1 arithmetic arithmetic operations
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
while python python python python code 1 arithmetic arithmetic operations x
